### ISSUE TITLE
fix: a computed title causes a duplicate meta script

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/unhead-schema-org#7]
### Describe the bug

See the minimal reproduction: when a **computed title** is used in `useHead`, adding `useSchemaOrg` leads to a duplicate `schema-org-graph`script appearing on client side hydration.

### Reproduction

https://stackblitz.com/edit/github-n9w3b7?file=app.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dargmuesli** [comment]
Updating from `v2.0.2` to `v2.0.7` resolved the problem! :)
